bind: 0.0.0.0
port: 8125
root: /data/batsd
redis:
  host: $REDIS_HOST
  port: 6379
retentions:
  10:  360 #1 hour
  60:  10080  #1 week (1 min inc)
  600: 52594 #1 year (10m inc)
  3600: 8760 #1 year (1 hour inc)
autotruncate: false
